/* Generated by wayland-scanner 1.22.0 */

/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2016 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * -------
 * Copyright © 2008-2011 Kristian Høgsberg
 * Copyright © 2010-2011 Intel Corporation
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that\n the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission.  The copyright holders make no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied
 * warranty.
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
 * SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
 * THIS SOFTWARE.
 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *simple_shell_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_surface_interface,
	NULL,
};

static const struct wl_message wl_simple_shell_requests[] = {
	{ "set_name", "us", simple_shell_types + 0 },
	{ "set_visible", "uu", simple_shell_types + 0 },
	{ "set_geometry", "uiiii", simple_shell_types + 0 },
	{ "set_opacity", "uf", simple_shell_types + 0 },
	{ "set_zorder", "uf", simple_shell_types + 0 },
	{ "get_status", "u", simple_shell_types + 0 },
	{ "get_surfaces", "", simple_shell_types + 0 },
	{ "set_focus", "u", simple_shell_types + 0 },
	{ "set_scale", "uff", simple_shell_types + 0 },
	{ "get_popup", "uuiiii", simple_shell_types + 0 },
	{ "is_surface_popup", "u", simple_shell_types + 0 },
};

static const struct wl_message wl_simple_shell_events[] = {
	{ "surface_id", "ou", simple_shell_types + 9 },
	{ "surface_created", "us", simple_shell_types + 0 },
	{ "surface_destroyed", "us", simple_shell_types + 0 },
	{ "surface_status", "usuiiiiff", simple_shell_types + 0 },
	{ "get_surfaces_done", "", simple_shell_types + 0 },
	{ "popup_details", "uui", simple_shell_types + 0 },
};

WL_PRIVATE const struct wl_interface wl_simple_shell_interface = {
	"wl_simple_shell", 1,
	11, wl_simple_shell_requests,
	6, wl_simple_shell_events,
};

