// SPDX-License-Identifier: MIT
/*
 * Copyright © 2011 Benjamin Franzke
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

// Build:
/* # Generate xdg-shell headers once (see below for exact commands)
    wayland-scanner client-header < /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml > xdg-shell-client-protocol.h
    wayland-scanner private-code < /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml > xdg-shell-protocol.c
   #compile wayland-egl and link deps
   gcc -Wall -Wextra -O0 -g -o wayland-egl-test wayland-egl.c xdg-shell-protocol.c \
       $(pkg-config --cflags --libs wayland-client wayland-egl egl glesv2) -lm 

*/
#define _POSIX_C_SOURCE 200809L
#include <assert.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include <wayland-client.h>
#include <wayland-egl.h>

#include <EGL/egl.h>
#include <GLES2/gl2.h>

// Generated by wayland-scanner (see build section)
#include "xdg-shell-client-protocol.h"

static volatile sig_atomic_t g_running = 1;

static void handle_sigint(int) { g_running = 0; }

static int32_t g_init_width  = 1280;
static int32_t g_init_height = 720;
static int     g_swap_interval = 1;

struct app {
    // Wayland
    struct wl_display     *wl_display;
    struct wl_registry    *wl_registry;
    struct wl_compositor  *wl_compositor;

    struct xdg_wm_base    *xdg_wm_base;
    struct wl_surface     *wl_surface;
    struct xdg_surface    *xdg_surface;
    struct xdg_toplevel   *xdg_toplevel;

    // EGL
    EGLDisplay  egl_display;
    EGLConfig   egl_config;
    EGLContext  egl_context;
    EGLSurface  egl_surface;

    struct wl_egl_window  *egl_window;

    // State
    int     have_configure;       // xdg_surface got first configure
    int     width, height;        // current size
    int     pending_width, pending_height; // size from last toplevel.configure
};

// ---------- Helpers & Checks ----------
static void die(const char *msg) {
    fprintf(stderr, "FATAL: %s\n", msg);
    exit(EXIT_FAILURE);
}

static void die_egl(const char *where) {
    EGLint err = eglGetError();
    fprintf(stderr, "FATAL EGL (%s): 0x%04x\n", where, err);
    exit(EXIT_FAILURE);
}

// ---------- xdg_wm_base ----------
static void xdg_wm_base_ping(void *data, struct xdg_wm_base *base, uint32_t serial) {
    (void)data;
    xdg_wm_base_pong(base, serial);
}
static const struct xdg_wm_base_listener xdg_wm_base_listener = {
    .ping = xdg_wm_base_ping,
};

// ---------- xdg_toplevel ----------
static void xdg_toplevel_configure(void *data,
                                   struct xdg_toplevel *toplevel,
                                   int32_t width, int32_t height,
                                   struct wl_array *states) {
    (void)toplevel; (void)states;
    struct app *a = data;

    // Compositors may send 0x0 (unspecified). Keep last if so.
    if (width  > 0) a->pending_width  = width;
    if (height > 0) a->pending_height = height;
}
static void xdg_toplevel_close(void *data, struct xdg_toplevel *toplevel) {
    (void)data;
    (void)toplevel;
    g_running = 0;
}
static void xdg_toplevel_configure_bounds(void *data,
                                          struct xdg_toplevel *toplevel,
                                          int32_t width, int32_t height)
{
    (void)data; (void)toplevel; (void)width; (void)height;
    /* Optionally store the compositor's suggested maximum bounds */
}
static void xdg_toplevel_wm_capabilities(void *data,
                                         struct xdg_toplevel *toplevel,
                                         struct wl_array *capabilities)
{
    (void)data; (void)toplevel; (void)capabilities;
    /* Optionally parse capabilities (uint32_t enums) if you care */
}
static const struct xdg_toplevel_listener xdg_toplevel_listener = {
    .configure = xdg_toplevel_configure,
    .close     = xdg_toplevel_close,
    .configure_bounds  = xdg_toplevel_configure_bounds,  // added since v5 of stable xdg
    .wm_capabilities   = xdg_toplevel_wm_capabilities,   // addded since v5 of stable xdg

};

// ---------- xdg_surface ----------
static void xdg_surface_configure(void *data, struct xdg_surface *surf, uint32_t serial) {
    struct app *a = data;

    // Acknowledge the configure (required by protocol)
    xdg_surface_ack_configure(surf, serial);

    // Use pending size if the compositor provided one; otherwise keep current
    int w = (a->pending_width  > 0) ? a->pending_width  : (a->width  > 0 ? a->width  : g_init_width);
    int h = (a->pending_height > 0) ? a->pending_height : (a->height > 0 ? a->height : g_init_height);

    // If EGL window exists, resize; else we’ll create it after first configure
    if (a->egl_window) {
        wl_egl_window_resize(a->egl_window, w, h, 0, 0);
    }
    a->width = w; a->height = h;

    a->have_configure = 1;
}

static const struct xdg_surface_listener xdg_surface_listener = {
    .configure = xdg_surface_configure,
};

// ---------- wl_registry ----------
static void handle_global(void *data, struct wl_registry *reg,
                          uint32_t name, const char *iface, uint32_t version) {
    struct app *a = data;

    if (strcmp(iface, "wl_compositor") == 0) {
        uint32_t v = version < 5 ? version : 5;
        a->wl_compositor = wl_registry_bind(reg, name, &wl_compositor_interface, v);
    } else if (strcmp(iface, "xdg_wm_base") == 0) {
        uint32_t v = version < 6 ? version : 6; // v6 common across compositors
        a->xdg_wm_base = wl_registry_bind(reg, name, &xdg_wm_base_interface, v);
        xdg_wm_base_add_listener(a->xdg_wm_base, &xdg_wm_base_listener, a);
    }
}
static void handle_global_remove(void *data, struct wl_registry *reg, uint32_t name) {
    (void)data; (void)reg; (void)name;
}
static const struct wl_registry_listener registry_listener = {
    .global        = handle_global,
    .global_remove = handle_global_remove,
};

// ---------- EGL Init ----------
static void egl_init(struct app *a) {
    a->egl_display = eglGetDisplay((EGLNativeDisplayType)a->wl_display);
    if (a->egl_display == EGL_NO_DISPLAY) die_egl("eglGetDisplay");

    if (!eglInitialize(a->egl_display, NULL, NULL)) die_egl("eglInitialize");

    if (!eglBindAPI(EGL_OPENGL_ES_API)) die_egl("eglBindAPI");

    // Choose a window-capable GLES2 config
    EGLint cfg_attribs[] = {
        EGL_SURFACE_TYPE,    EGL_WINDOW_BIT,
        EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,
        EGL_RED_SIZE,        8,
        EGL_GREEN_SIZE,      8,
        EGL_BLUE_SIZE,       8,
        EGL_ALPHA_SIZE,      8,
        EGL_NONE
    };
    EGLint num = 0;
    if (!eglChooseConfig(a->egl_display, cfg_attribs, &a->egl_config, 1, &num) || num < 1)
        die_egl("eglChooseConfig");

    EGLint ctx_attribs[] = { EGL_CONTEXT_CLIENT_VERSION, 2, EGL_NONE };
    a->egl_context = eglCreateContext(a->egl_display, a->egl_config, EGL_NO_CONTEXT, ctx_attribs);
    if (a->egl_context == EGL_NO_CONTEXT) die_egl("eglCreateContext");
}

static void create_surface_chain(struct app *a) {
    // Wayland wl_surface
    a->wl_surface = wl_compositor_create_surface(a->wl_compositor);
    if (!a->wl_surface) die("wl_compositor_create_surface failed");

    // xdg_surface / xdg_toplevel
    a->xdg_surface = xdg_wm_base_get_xdg_surface(a->xdg_wm_base, a->wl_surface);
    if (!a->xdg_surface) die("xdg_wm_base_get_xdg_surface failed");
    xdg_surface_add_listener(a->xdg_surface, &xdg_surface_listener, a);

    a->xdg_toplevel = xdg_surface_get_toplevel(a->xdg_surface);
    if (!a->xdg_toplevel) die("xdg_surface_get_toplevel failed");
    xdg_toplevel_add_listener(a->xdg_toplevel, &xdg_toplevel_listener, a);

    xdg_toplevel_set_app_id(a->xdg_toplevel, "wayland-egl-sample");
    xdg_toplevel_set_title(a->xdg_toplevel,  "Wayland EGL Sample");

    // Commit the initial empty surface to trigger first configure
    wl_surface_commit(a->wl_surface);
    wl_display_flush(a->wl_display);

    // Wait until we receive the first xdg_surface.configure (and size)
    while (!a->have_configure) {
        if (wl_display_dispatch(a->wl_display) < 0) die("wl_display_dispatch failed (configure)");
    }

    // Create wl_egl_window with negotiated size
    if (a->width <= 0)  a->width  = g_init_width;
    if (a->height <= 0) a->height = g_init_height;

    a->egl_window = wl_egl_window_create(a->wl_surface, a->width, a->height);
    if (!a->egl_window) die("wl_egl_window_create failed");

    // Create EGLSurface for the native (wl_egl_window) window
    a->egl_surface = eglCreateWindowSurface(
        a->egl_display, a->egl_config,
        (EGLNativeWindowType)a->egl_window,
        NULL
    );
    if (a->egl_surface == EGL_NO_SURFACE) die_egl("eglCreateWindowSurface");

    if (!eglMakeCurrent(a->egl_display, a->egl_surface, a->egl_surface, a->egl_context))
        die_egl("eglMakeCurrent");

    // Swap interval (can be overridden via env)
    eglSwapInterval(a->egl_display, g_swap_interval);
}

// ---------- Render ----------
static void render_frame(struct app *a, float t) {
    // Simple animated color; replace with real GL content as needed
    float green = 0.5f + 0.5f * (float)sinf(t);
    glViewport(0, 0, a->width, a->height);
    glClearColor(0.0f, green, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);

    eglSwapBuffers(a->egl_display, a->egl_surface);
}

// ---------- Env parsing ----------
static void load_env_overrides(void) {
    const char *w = getenv("WIDTH");
    const char *h = getenv("HEIGHT");
    const char *si = getenv("SWAP_INTERVAL");
    if (w)  g_init_width = atoi(w);
    if (h)  g_init_height = atoi(h);
    if (si) g_swap_interval = atoi(si);
}

// ---------- Main ----------
int main(void) {
    signal(SIGINT,  handle_sigint);
    signal(SIGTERM, handle_sigint);
    load_env_overrides();

    struct app a = {0};

    // 1) Connect + registry
    a.wl_display = wl_display_connect(NULL);
    if (!a.wl_display) die("wl_display_connect failed");

    a.wl_registry = wl_display_get_registry(a.wl_display);
    if (!a.wl_registry) die("wl_display_get_registry failed");
    wl_registry_add_listener(a.wl_registry, &registry_listener, &a);

    // Dispatch until compositor & xdg_wm_base are bound
    wl_display_roundtrip(a.wl_display);
    wl_display_roundtrip(a.wl_display);
    if (!a.wl_compositor) die("wl_compositor not advertised");
    if (!a.xdg_wm_base)  die("xdg_wm_base not advertised");

    // 2) EGL init
    egl_init(&a);

    // 3) Create wl_surface → xdg_surface/toplevel → wl_egl_window → EGLSurface
    create_surface_chain(&a);

    // 4) Main loop
    double tick = 0.0;
    while (g_running) {
        // Process events without blocking forever, then render one frame
        while (wl_display_prepare_read(a.wl_display) != 0) {
            wl_display_dispatch_pending(a.wl_display);
        }
        wl_display_flush(a.wl_display);
        wl_display_read_events(a.wl_display);
        wl_display_dispatch_pending(a.wl_display);

        // Draw
        render_frame(&a, (float)tick);
        tick += 0.016; // ~60 FPS tick
    }

    // 5) Cleanup
    if (a.egl_display) {
        eglMakeCurrent(a.egl_display, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
        if (a.egl_surface) eglDestroySurface(a.egl_display, a.egl_surface);
        if (a.egl_context) eglDestroyContext(a.egl_display, a.egl_context);
        eglTerminate(a.egl_display);
    }
    if (a.egl_window)   wl_egl_window_destroy(a.egl_window);
    if (a.xdg_toplevel) xdg_toplevel_destroy(a.xdg_toplevel);
    if (a.xdg_surface)  xdg_surface_destroy(a.xdg_surface);
    if (a.wl_surface)   wl_surface_destroy(a.wl_surface);
    if (a.xdg_wm_base)  xdg_wm_base_destroy(a.xdg_wm_base);
    if (a.wl_compositor) wl_compositor_destroy(a.wl_compositor);
    if (a.wl_registry)  wl_registry_destroy(a.wl_registry);
    if (a.wl_display)   wl_display_disconnect(a.wl_display);
    return 0;
}

