// SPDX-License-Identifier: MIT
/*
 * Wayland + EGL sample that:
 *  - Prefers Westeros wl_simple_shell when available (listen to surface_id, set_name)
 *  - Falls back to xdg_wm_base on non-Westeros compositors
 *
 * Build notes :
 
 wayland-scanner client-header \
  < /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
  > xdg-shell-client-protocol.h

wayland-scanner private-code \
  < /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
  > xdg-shell-protocol.c

wayland-scanner client-header \
  < ./simpleshell.xml \
  > simpleshell-client-protocol.h

wayland-scanner private-code \
  < ./simpleshell.xml \
  > simpleshell-protocol.c

gcc -Wall -Wextra -O0 -g -o wayland-egl-simpleshell-test \
  wayland-egl-simpleshell.c \
  xdg-shell-protocol.c \
  simpleshell-protocol.c \
  $(pkg-config --cflags --libs wayland-client wayland-egl egl glesv2) \
  -lm
 *
 */

#define _POSIX_C_SOURCE 200809L
#include <assert.h>
#include <signal.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include <wayland-client.h>
#include <wayland-egl.h>

#include <EGL/egl.h>
#include <GLES2/gl2.h>

/* Generated by wayland-scanner (see build section) */
#include "xdg-shell-client-protocol.h"
#include "simpleshell-client-protocol.h"  /* generated from simpleshell.xml */

/* ---------------- Runtime configuration ---------------- */
static volatile sig_atomic_t g_running = 1;
static void handle_sigint(int) { g_running = 0; }

static int32_t g_init_width  = 1280;
static int32_t g_init_height = 720;
static int     g_swap_interval = 1;

/* ---------------- Application state ---------------- */
struct app {
    /* Wayland core */
    struct wl_display     *wl_display;
    struct wl_registry    *wl_registry;
    struct wl_compositor  *wl_compositor;

    /* SimpleShell (Westeros) */
    struct wl_simple_shell *wl_simple_shell;   /* global */
    uint32_t                ss_surface_id;     /* surfaceId received via surface_id event */
    bool                    ss_active;         /* we’re running in SimpleShell mode once surface_id arrives */

    /* xdg-shell (fallback) */
    struct xdg_wm_base    *xdg_wm_base;
    struct wl_surface     *wl_surface;
    struct xdg_surface    *xdg_surface;
    struct xdg_toplevel   *xdg_toplevel;

    /* EGL */
    EGLDisplay  egl_display;
    EGLConfig   egl_config;
    EGLContext  egl_context;
    EGLSurface  egl_surface;
    struct wl_egl_window *egl_window;

    /* state */
    int have_configure;              /* xdg_surface first configure received */
    int width, height;               /* current size */
    int pending_width, pending_height; /* xdg_toplevel.configure suggested size */

    /* mode */
    bool prefer_simpleshell;         /* set when wl_simple_shell global is present */
};

/* ---------------- Helpers ---------------- */
static void die(const char *msg) {
    fprintf(stderr, "FATAL: %s\n", msg);
    exit(EXIT_FAILURE);
}
static void die_egl(const char *where) {
    EGLint err = eglGetError();
    fprintf(stderr, "FATAL EGL (%s): 0x%04x\n", where, err);
    exit(EXIT_FAILURE);
}
static void load_env_overrides(void) {
    const char *w = getenv("WIDTH");
    const char *h = getenv("HEIGHT");
    const char *si = getenv("SWAP_INTERVAL");
    if (w)  g_init_width = atoi(w);
    if (h)  g_init_height = atoi(h);
    if (si) g_swap_interval = atoi(si);
}

/* ---------------- xdg_wm_base ---------------- */
static void xdg_wm_base_ping(void *data, struct xdg_wm_base *base, uint32_t serial) {
    (void)data;
    xdg_wm_base_pong(base, serial);
}
static const struct xdg_wm_base_listener xdg_wm_base_listener = {
    .ping = xdg_wm_base_ping,
};

/* ---------------- xdg_toplevel ---------------- */
static void xdg_toplevel_configure(void *data, struct xdg_toplevel *toplevel,
                                   int32_t width, int32_t height,
                                   struct wl_array *states) {
    (void)toplevel; (void)states;
    struct app *a = data;
    if (width  > 0) a->pending_width  = width;
    if (height > 0) a->pending_height = height;
}
static void xdg_toplevel_close(void *data, struct xdg_toplevel *toplevel) {
    (void)data; (void)toplevel;
    g_running = 0;
}
static void xdg_toplevel_configure_bounds(void *data, struct xdg_toplevel *toplevel,
                                          int32_t width, int32_t height) {
    (void)data; (void)toplevel; (void)width; (void)height;
}
static void xdg_toplevel_wm_capabilities(void *data, struct xdg_toplevel *toplevel,
                                         struct wl_array *capabilities) {
    (void)data; (void)toplevel; (void)capabilities;
}
static const struct xdg_toplevel_listener xdg_toplevel_listener = {
    .configure         = xdg_toplevel_configure,
    .close             = xdg_toplevel_close,
    .configure_bounds  = xdg_toplevel_configure_bounds,
    .wm_capabilities   = xdg_toplevel_wm_capabilities,
};

/* ---------------- xdg_surface ---------------- */
static void xdg_surface_configure(void *data, struct xdg_surface *surf, uint32_t serial) {
    struct app *a = data;
    xdg_surface_ack_configure(surf, serial);

    int w = (a->pending_width  > 0) ? a->pending_width  : (a->width  > 0 ? a->width  : g_init_width);
    int h = (a->pending_height > 0) ? a->pending_height : (a->height > 0 ? a->height : g_init_height);

    if (a->egl_window) wl_egl_window_resize(a->egl_window, w, h, 0, 0);
    a->width = w; a->height = h;
    a->have_configure = 1;
}
static const struct xdg_surface_listener xdg_surface_listener = {
    .configure = xdg_surface_configure,
};

/* ---------------- SimpleShell (client) ----------------
 * According to simpleshell.xml:
 *  - global interface: wl_simple_shell (v1)
 *  - event: surface_id(wl_surface, uint) sent to the creator of the surface
 *  - request: set_name(surfaceId, string)
 * (Other requests exist but are often privileged; we leave them commented.)
 */
static void ss_surface_id(void *data, struct wl_simple_shell *shell,
                          struct wl_surface *surface, uint32_t surfaceId) {
    struct app *a = data;
    (void)shell;

    /* Match against our surface; Westeros sends this to the creator */
    if (surface == a->wl_surface) {
        a->ss_surface_id = surfaceId;
        a->ss_active = true;
        /* Safe and intended for regular clients: name the surface */
        wl_simple_shell_set_name(a->wl_simple_shell, surfaceId, "wayland-egl-simpleshell");

        /* Optional (commented): these are often reserved for AppController
           wl_simple_shell_set_visible(a->wl_simple_shell, surfaceId, 1);
           wl_simple_shell_set_geometry(a->wl_simple_shell, surfaceId, 0, 0, a->width, a->height);
           wl_simple_shell_set_opacity(a->wl_simple_shell, surfaceId, wl_fixed_from_double(1.0));
           wl_simple_shell_set_focus(a->wl_simple_shell, surfaceId);
        */
        fprintf(stderr, "[simpleshell] surface_id received: %u (named)\n", surfaceId);
    }
}
static void ss_surface_created(void *data, struct wl_simple_shell *shell,
                               uint32_t surfaceId, const char *name) {
    (void)data; (void)shell; (void)surfaceId; (void)name;
    /* broadcast event for all clients; optional to log */
}
static void ss_surface_destroyed(void *data, struct wl_simple_shell *shell,
                                 uint32_t surfaceId, const char *name) {
    (void)data; (void)shell; (void)surfaceId; (void)name;
}
static void ss_surface_status(void *data, struct wl_simple_shell *shell,
                              uint32_t surfaceId, const char *name, uint32_t visible,
                              int32_t x, int32_t y, int32_t w, int32_t h,
                              wl_fixed_t opacity, wl_fixed_t zorder) {
    (void)data; (void)shell; (void)surfaceId; (void)name;
    (void)visible; (void)x; (void)y; (void)w; (void)h; (void)opacity; (void)zorder;
}
static void ss_get_surfaces_done(void *data, struct wl_simple_shell *shell) {
    (void)data; (void)shell;
}
static void ss_popup_details(void *data, struct wl_simple_shell *shell,
                             uint32_t surfaceId, uint32_t parentSurfaceId, int32_t popup) {
    (void)data; (void)shell; (void)surfaceId; (void)parentSurfaceId; (void)popup;
}
static const struct wl_simple_shell_listener ss_listener = {
    .surface_id         = ss_surface_id,
    .surface_created    = ss_surface_created,
    .surface_destroyed  = ss_surface_destroyed,
    .surface_status     = ss_surface_status,
    .get_surfaces_done  = ss_get_surfaces_done,
    .popup_details      = ss_popup_details,
};

/* ---------------- Registry ---------------- */
static void handle_global(void *data, struct wl_registry *reg,
                          uint32_t name, const char *iface, uint32_t version) {
    struct app *a = data;

    if (strcmp(iface, "wl_compositor") == 0) {
        uint32_t v = version < 5 ? version : 5;
        a->wl_compositor = wl_registry_bind(reg, name, &wl_compositor_interface, v);

    } else if (strcmp(iface, "wl_simple_shell") == 0) {
        /* Prefer SimpleShell mode on Westeros */
        a->wl_simple_shell = wl_registry_bind(reg, name, &wl_simple_shell_interface, 1);
        wl_simple_shell_add_listener(a->wl_simple_shell, &ss_listener, a);
        a->prefer_simpleshell = true; /* we’ll use it if possible */
        /* No per-surface object is created: compositor will emit surface_id after wl_surface creation. */

    } else if (strcmp(iface, "xdg_wm_base") == 0) {
        /* Fallback windowing when SimpleShell is absent */
        uint32_t v = version < 6 ? version : 6;
        a->xdg_wm_base = wl_registry_bind(reg, name, &xdg_wm_base_interface, v);
        xdg_wm_base_add_listener(a->xdg_wm_base, &xdg_wm_base_listener, a);
    }
}
static void handle_global_remove(void *data, struct wl_registry *reg, uint32_t name) {
    (void)data; (void)reg; (void)name;
}
static const struct wl_registry_listener registry_listener = {
    .global        = handle_global,
    .global_remove = handle_global_remove,
};

/* ---------------- EGL init ---------------- */
static void egl_init(struct app *a) {
    a->egl_display = eglGetDisplay((EGLNativeDisplayType)a->wl_display);
    if (a->egl_display == EGL_NO_DISPLAY) die_egl("eglGetDisplay");
    if (!eglInitialize(a->egl_display, NULL, NULL)) die_egl("eglInitialize");
    if (!eglBindAPI(EGL_OPENGL_ES_API)) die_egl("eglBindAPI");

    EGLint cfg_attribs[] = {
        EGL_SURFACE_TYPE,    EGL_WINDOW_BIT,
        EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,
        EGL_RED_SIZE,        8,
        EGL_GREEN_SIZE,      8,
        EGL_BLUE_SIZE,       8,
        EGL_ALPHA_SIZE,      8,
        EGL_NONE
    };
    EGLint num = 0;
    if (!eglChooseConfig(a->egl_display, cfg_attribs, &a->egl_config, 1, &num) || num < 1)
        die_egl("eglChooseConfig");

    EGLint ctx_attribs[] = { EGL_CONTEXT_CLIENT_VERSION, 2, EGL_NONE };
    a->egl_context = eglCreateContext(a->egl_display, a->egl_config, EGL_NO_CONTEXT, ctx_attribs);
    if (a->egl_context == EGL_NO_CONTEXT) die_egl("eglCreateContext");
}

/* ---------------- Surface creation paths ---------------- */

/* SimpleShell path: create wl_surface, wait for surface_id, then proceed */
static void create_surface_simpleshell(struct app *a) {
    a->wl_surface = wl_compositor_create_surface(a->wl_compositor);
    if (!a->wl_surface) die("wl_compositor_create_surface failed (SimpleShell)");

    /* We don’t create xdg roles in SimpleShell mode. The compositor will emit
       wl_simple_shell.surface_id(surface, id) to this client.*/
    wl_surface_commit(a->wl_surface);
    wl_display_flush(a->wl_display);

    /* Make sure we have a size to build the EGL window */
    a->width  = (a->width  > 0) ? a->width  : g_init_width;
    a->height = (a->height > 0) ? a->height : g_init_height;

    /* Wait until we receive surface_id for our wl_surface */
    while (!a->ss_active && g_running) {
        if (wl_display_dispatch(a->wl_display) < 0) die("dispatch failed (waiting for surface_id)");
    }

    /* Create wl_egl_window and EGLSurface */
    a->egl_window = wl_egl_window_create(a->wl_surface, a->width, a->height);
    if (!a->egl_window) die("wl_egl_window_create failed (SimpleShell)");

    a->egl_surface = eglCreateWindowSurface(
        a->egl_display, a->egl_config,
        (EGLNativeWindowType)a->egl_window,
        NULL
    );
    if (a->egl_surface == EGL_NO_SURFACE) die_egl("eglCreateWindowSurface (SimpleShell)");

    if (!eglMakeCurrent(a->egl_display, a->egl_surface, a->egl_surface, a->egl_context))
        die_egl("eglMakeCurrent (SimpleShell)");

    eglSwapInterval(a->egl_display, g_swap_interval);
}

/* xdg-shell path: create xdg_surface/toplevel, wait for configure */
static void create_surface_xdg(struct app *a) {
    a->wl_surface = wl_compositor_create_surface(a->wl_compositor);
    if (!a->wl_surface) die("wl_compositor_create_surface failed (xdg)");

    a->xdg_surface = xdg_wm_base_get_xdg_surface(a->xdg_wm_base, a->wl_surface);
    if (!a->xdg_surface) die("xdg_wm_base_get_xdg_surface failed");
    xdg_surface_add_listener(a->xdg_surface, &xdg_surface_listener, a);

    a->xdg_toplevel = xdg_surface_get_toplevel(a->xdg_surface);
    if (!a->xdg_toplevel) die("xdg_surface_get_toplevel failed");
    xdg_toplevel_add_listener(a->xdg_toplevel, &xdg_toplevel_listener, a);
    xdg_toplevel_set_app_id(a->xdg_toplevel, "wayland-egl-sample");
    xdg_toplevel_set_title(a->xdg_toplevel,  "Wayland EGL Sample");

    wl_surface_commit(a->wl_surface);
    wl_display_flush(a->wl_display);

    /* Wait for the first configure (xdg) */
    while (!a->have_configure && g_running) {
        if (wl_display_dispatch(a->wl_display) < 0) die("dispatch failed (waiting for xdg configure)");
    }

    /* Negotiate size or use defaults */
    a->width  = (a->width  > 0) ? a->width  : g_init_width;
    a->height = (a->height > 0) ? a->height : g_init_height;

    a->egl_window = wl_egl_window_create(a->wl_surface, a->width, a->height);
    if (!a->egl_window) die("wl_egl_window_create failed (xdg)");

    a->egl_surface = eglCreateWindowSurface(
        a->egl_display, a->egl_config,
        (EGLNativeWindowType)a->egl_window,
        NULL
    );
    if (a->egl_surface == EGL_NO_SURFACE) die_egl("eglCreateWindowSurface (xdg)");

    if (!eglMakeCurrent(a->egl_display, a->egl_surface, a->egl_surface, a->egl_context))
        die_egl("eglMakeCurrent (xdg)");

    eglSwapInterval(a->egl_display, g_swap_interval);
}

/* ---------------- Rendering ---------------- */
static void render_frame(struct app *a, float t) {
    float green = 0.5f + 0.5f * sinf(t);
    glViewport(0, 0, a->width, a->height);
    glClearColor(0.0f, green, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);
    eglSwapBuffers(a->egl_display, a->egl_surface);
}

/* ---------------- Main ---------------- */
int main(void) {
    signal(SIGINT,  handle_sigint);
    signal(SIGTERM, handle_sigint);
    load_env_overrides();

    struct app a = {0};

    /* Connect + registry */
    const char *display_name = getenv("WAYLAND_DISPLAY");
    if (!display_name) {
        display_name = "wayland-0";
    }
    fprintf(stderr, "[INFO] requestion connection to WAYLAND_DISPLAY = \"%s\"\n", display_name);
    a.wl_display = wl_display_connect(display_name);
    if (!a.wl_display) {
         fprintf(stderr, "[ERROR] wl_display_connect(\"%s\") failed\n", display_name);
         die("wl_display_connect failed");
    }

    a.wl_registry = wl_display_get_registry(a.wl_display);
    if (!a.wl_registry) die("wl_display_get_registry failed");
    wl_registry_add_listener(a.wl_registry, &registry_listener, &a);

    /* Roundtrips to bind globals (compositor, wl_simple_shell or xdg_wm_base) */
    wl_display_roundtrip(a.wl_display);
    wl_display_roundtrip(a.wl_display);
    if (!a.wl_compositor) die("wl_compositor not advertised");

    /* Initialize EGL */
    egl_init(&a);

    /* Prefer SimpleShell if present; otherwise use xdg-shell */
    if (a.prefer_simpleshell && a.wl_simple_shell) {
        fprintf(stderr, "[mode] Using wl_simple_shell path\n");
        create_surface_simpleshell(&a);
    } else {
        if (!a.xdg_wm_base) die("xdg_wm_base not advertised and wl_simple_shell absent");
        fprintf(stderr, "[mode] Using xdg_wm_base fallback\n");
        create_surface_xdg(&a);
    }

    /* Main loop */
    double tick = 0.0;
    while (g_running) {
        /* Cooperative non-blocking event loop */
        while (wl_display_prepare_read(a.wl_display) != 0) {
            wl_display_dispatch_pending(a.wl_display);
        }
        wl_display_flush(a.wl_display);
        if (wl_display_read_events(a.wl_display) < 0) break;
        wl_display_dispatch_pending(a.wl_display);

        /* Draw */
        render_frame(&a, (float)tick);
        tick += 0.016; /* ~60 FPS tick */
    }

    /* Cleanup */
    if (a.egl_display) {
        eglMakeCurrent(a.egl_display, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
        if (a.egl_surface) eglDestroySurface(a.egl_display, a.egl_surface);
        if (a.egl_context) eglDestroyContext(a.egl_display, a.egl_context);
        eglTerminate(a.egl_display);
    }
    if (a.egl_window)   wl_egl_window_destroy(a.egl_window);

    /* Destroy roles only in xdg mode */
    if (!a.ss_active) {
        if (a.xdg_toplevel) xdg_toplevel_destroy(a.xdg_toplevel);
        if (a.xdg_surface)  xdg_surface_destroy(a.xdg_surface);
    }

    if (a.wl_surface)   wl_surface_destroy(a.wl_surface);
    if (a.wl_simple_shell) wl_simple_shell_destroy(a.wl_simple_shell);
    if (a.xdg_wm_base)  xdg_wm_base_destroy(a.xdg_wm_base);
    if (a.wl_compositor) wl_compositor_destroy(a.wl_compositor);
    if (a.wl_registry)  wl_registry_destroy(a.wl_registry);
    if (a.wl_display)   wl_display_disconnect(a.wl_display);
    return 0;
}

